### ISSUE TITLE
I entered the following command 'python3 -m openpifpaf.predict test1.jpg --checkpoint resnet50' and the error come outs,how can i deal with it?

### ISSUE THREAD

**Issue by xiaochehe** [vita-epfl/openpifpaf#153]
I entered the following command 'python3 -m openpifpaf.predict test1.jpg --checkpoint resnet50' and the error come outs,how can i deal with it?
`/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/serialization.py:452: SourceChangeWarning: source code of class 'openpifpaf.network.nets.Shell' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/serialization.py:452: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/serialization.py:452: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/serialization.py:452: SourceChangeWarning: source code of class 'openpifpaf.network.heads.CompositeField' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/biancunling/openpifpaf/openpifpaf/predict.py", line 174, in <module>
    main()
  File "/home/biancunling/openpifpaf/openpifpaf/predict.py", line 121, in main
    fields_batch = processor.fields(image_tensors_batch_gpu)
  File "/home/biancunling/openpifpaf/openpifpaf/decoder/processor.py", line 71, in fields
    heads = self.model(image_batch)
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/biancunling/openpifpaf/openpifpaf/network/nets.py", line 38, in forward
    x = self.base_net(*args)
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/biancunling/openpifpaf/openpifpaf/network/basenetworks.py", line 39, in forward
    return self.net(image)
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 97, in forward
    input = module(input)
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 97, in forward
    input = module(input)
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 50, in forward
    return F.threshold(input, self.threshold, self.value, self.inplace)
  File "/home/biancunling/anaconda3/envs/python36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 537, in __getattr__
    type(self).__name__, name))
AttributeError: 'ReLU' object has no attribute 'threshold'
`

**Comment by svenkreiss** [comment]
Which version of pytorch is this? Can you try to update if less than 1.1?

**Comment by xiaochehe** [comment]
Thanks, I will update my pytorch to more than 1.1. My pytorch version is only 1.0 now.
