### ISSUE TITLE
Error while changing the --square-edge parameter

### ISSUE THREAD

**Issue by anant15** [vita-epfl/openpifpaf#194]
I am trying to improve the performance of the Resnet-18 model on my custom dataset using the estimates of Resnet-152 as the ground truth for fine-tuning the Resnet-18 model. My images are of size 1920X980. After a recent train fixing, I could train the model and the training went as I feel from the plots.

![image](https://user-images.githubusercontent.com/54929615/77047901-8bafb280-69eb-11ea-9ed0-d09dc78f8ad5.png)

But when I tried checking the results qualitatively, they seem really bad - even on the training and validation set. I suspect that this is happening probably because of difference in the input scale. By default, during the training and validation, the images are scaled to 401X401, and during testing using predict.py, I only used the original and the //2 (850X420) scale of the images.

After this, I tried changing the training code where I changed the --square-edge parameters to be the same as the long edge of the input image but nasty errors started showing up.

```
Traceback (most recent call last):
  File "/nfs/interns/anantm/anaconda2/envs/pytorch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nfs/interns/anantm/anaconda2/envs/pytorch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfs/nas2VehiScan/IMPData/Video_Analytics/factoryData/factory-anant/openpifpaf-10/openpifpaf/train.py", line 206, in <module>
    main()
  File "/nfs/nas2VehiScan/IMPData/Video_Analytics/factoryData/factory-anant/openpifpaf-10/openpifpaf/train.py", line 202, in main
    trainer.loop(train_loader, val_loader, args.epochs, start_epoch=start_epoch)
  File "/nfs/nas2VehiScan/IMPData/Video_Analytics/factoryData/factory-anant/openpifpaf-10/openpifpaf/network/trainer.py", line 99, in loop
    self.train(train_scenes, epoch)
  File "/nfs/nas2VehiScan/IMPData/Video_Analytics/factoryData/factory-anant/openpifpaf-10/openpifpaf/network/trainer.py", line 173, in train
    loss, head_losses = self.train_batch(data, target, meta, apply_gradients)
  File "/nfs/nas2VehiScan/IMPData/Video_Analytics/factoryData/factory-anant/openpifpaf-10/openpifpaf/network/trainer.py", line 116, in train_batch
    loss, head_losses = self.loss(outputs, targets)
  File "/nfs/interns/anantm/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfs/nas2VehiScan/IMPData/Video_Analytics/factoryData/factory-anant/openpifpaf-10/openpifpaf/network/losses.py", line 136, in forward
    for l, f, t in zip(self.losses, head_fields, head_targets)
  File "/nfs/nas2VehiScan/IMPData/Video_Analytics/factoryData/factory-anant/openpifpaf-10/openpifpaf/network/losses.py", line 137, in <listcomp>
    for ll in l(f, t)]
  File "/nfs/interns/anantm/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/nfs/nas2VehiScan/IMPData/Video_Analytics/factoryData/factory-anant/openpifpaf-10/openpifpaf/network/losses.py", line 266, in forward
    torch.masked_select(bce_x_intensity, bce_masks),
RuntimeError: The size of tensor a (57) must match the size of tensor b (58) at non-singleton dimension 3
```
Any help in solving this error so that my training can be performed on different square-edge sizes or any recommendations towards my overall procedure would be really appreciated.

**Comment by svenkreiss** [comment]
Most important thing is to use image edge sizes that are multiples of 16
plus 1 (the plus one is important): 16*n+1
That will probably solve this particular error.

In detection and keypoint estimation, image size is not that relevant (that
is different from image classification). What matters is that your objects
have the same size in pixels during training and testing.
So if you look at people in training that are 50px high, they should also
be 50px high during testing. That they are in an image with an edge size of
401px or 1921px is not that relevant.

**Comment by anant15** [comment]
Thanks for quick responses, will look into the problem accordingly. Thanks a lot.
