### ISSUE TITLE
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by taufeeque9** [vita-epfl/openpifpaf#211]
I'm getting this error when running `python3 -m openpifpaf.video` with v0.11.1. This error never came in v0.10.1. No error comes when running the openpifpaf.predict command. The error maybe has something to do with torch.unsqueeze(processed_image, 0) used in video.py.
Here are the details:
```INFO:openpifpaf.show.animation_frame:video output = None
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/taufeeque/.local/lib/python3.6/site-packages/openpifpaf/video.py", line 201, in <module>
    main()
  File "/home/taufeeque/.local/lib/python3.6/site-packages/openpifpaf/video.py", line 177, in main
    preds = processor.batch(model, torch.unsqueeze(processed_image, 0), device=args.device)[0]
  File "/home/taufeeque/.local/lib/python3.6/site-packages/openpifpaf/decoder/generator/generator.py", line 97, in batch
    self._mappable_annotations, zip(fields_batch, image_batch))
  File "/home/taufeeque/.local/lib/python3.6/site-packages/openpifpaf/decoder/generator/generator.py", line 17, in starmap
    return [f(*i) for i in iterable]
  File "/home/taufeeque/.local/lib/python3.6/site-packages/openpifpaf/decoder/generator/generator.py", line 17, in <listcomp>
    return [f(*i) for i in iterable]
  File "/home/taufeeque/.local/lib/python3.6/site-packages/openpifpaf/decoder/generator/generator.py", line 105, in _mappable_annotations
    visualizer.BaseVisualizer.processed_image(debug_image)
  File "/home/taufeeque/.local/lib/python3.6/site-packages/openpifpaf/visualizer/base.py", line 48, in processed_image
    image = np.moveaxis(np.asarray(image), 0, -1)
  File "/home/taufeeque/.local/lib/python3.6/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/taufeeque/.local/lib/python3.6/site-packages/torch/tensor.py", line 486, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.```

**Comment by svenkreiss** [comment]
Hi @taufeeque9 . Thanks for this report. `openpifpaf.video` is usually not tested with cuda, so you probably found a bug there. I will look into this.
