### ISSUE TITLE
Running to error of AttributeError: 'Shell' object has no attribute 'head_names'

### ISSUE THREAD

**Issue by rabysam28** [vita-epfl/openpifpaf#246]
Here is how I install and run it:
conda activate testbed
cd ~/Downloads
git clone https://github.com/vita-epfl/openpifpaf.git
cd openpifpaf
rm -rf ./openpifpaf/ [you said this needs to be done]
python3.7 -m pip install openpifpaf [this succeeds fine]
python3.7 -m openpifpaf.predict coco/000000081988.jpg --image-output

and I am getting the following error. What is causing this error? 

INFO:__main__:Using multiple GPUs: 4
Traceback (most recent call last):
  File "~/anaconda3/envs/testbed/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "~/anaconda3/envs/testbed/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/anaconda3/envs/testbed/lib/python3.7/site-packages/openpifpaf/predict.py", line 207, in <module>
    main()
  File "~/anaconda3/envs/testbed/lib/python3.7/site-packages/openpifpaf/predict.py", line 153, in main
    processor, model = processor_factory(args)
  File "~/anaconda3/envs/testbed/lib/python3.7/site-packages/openpifpaf/predict.py", line 107, in processor_factory
    model.head_names = model_cpu.head_names
  File "~/anaconda3/envs/testbed/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'Shell' object has no attribute 'head_names'

**Comment by svenkreiss** [comment]
You have a version mismatch of some form.
You have two ways to install openpifpaf. Do not mix them:

1) For developers of openpifpaf code: Clone the repository and install with `pip install -e .`.
2) For everyone else: Do __not__ clone the repository and install with `pip install openpifpaf`.

Before trying again, make sure you have no conflict. I would run `pip uninstall openpifpaf` at least twice until it says that it cannot find openpifpaf anymore.

**Comment by Jill0001** [comment]
Hi, I encountered the same problem, I first ensured I didn't install openpifpaf by running `pip uninstall openpifpaf` and I got ` Skipping openpifpaf as it is not installed`.
Then I cloned the repo and installed with ` pip3 install -e . --user` as you said above.
but I still get the same error : `'Shell' object has no attribute 'head_names'` when I run this command `python3 -m openpifpaf.predict coco/000000081988.jpg --image-output --json-output --debug`
I couldn't figure out why, do you know how to fix this problem? 
Thanks

**Comment by svenkreiss** [comment]
Can you post the full stack track?

**Comment by svenkreiss** [comment]
I think I spotted a problem.

Try to prefix your predict command with `CUDA_VISIBLE_DEVICES=0`. It seems to try multi-gpu prediction which isn't tested well. I will add a fix though because this shouldn't happen. Thanks for reporting!

**Comment by rabysam28** [comment]
Hi Sven, I did what you recommended, and also did a git pull and re-installed the latest. I am running to a new issue as shown below:

INFO:__main__:batch 0: coco/000000081988.jpg
Traceback (most recent call last):
  File "anaconda3/envs/testbed/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/myuser/anaconda3/envs/testbed/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/myuser/Downloads/openpifpaf/openpifpaf/predict.py", line 207, in <module>
    main()
  File "/home/myuser/Downloads/openpifpaf/openpifpaf/predict.py", line 202, in main
    dpi_factor=args.dpi_factor) as ax:
  File "/home/myuser/anaconda3/envs/testbed/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/myuser/Downloads/openpifpaf/openpifpaf/show/canvas.py", line 45, in image_canvas
    fig = plt.figure(**kwargs)
AttributeError: 'NoneType' object has no attribute 'figure'

**Comment by svenkreiss** [comment]
Indeed, you will need to install `matplotlib` to produce output images. I just updated the docs to make that clear.

**Comment by rabysam28** [comment]
Great. that fixed it. Thanks!

**Comment by svenkreiss** [comment]
Great to hear. Thanks for reporting this. I am sure this will make the start easier for future users.
