### ISSUE TITLE
Assertion error when going to second epoch

### ISSUE THREAD

**Issue by gondimjoaom** [vita-epfl/openpifpaf#264]
Hi, here I go again.

I had a small own coco like dataset which trained just fine, and now I'm trying to use a new extended onde, but I'm having an assertion error when one of the epochs is trained.

`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/train.py", line 143, in <module>
    main()
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/train.py", line 139, in main
    trainer.loop(train_loader, val_loader, args.epochs, start_epoch=start_epoch)
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/network/trainer.py", line 101, in loop
    self.train(train_scenes, epoch)
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/network/trainer.py", line 167, in train
    for batch_idx, (data, target, _) in enumerate(scenes):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/datasets/coco.py", line 168, in __getitem__
    anns = [t(image, anns, meta) for t in self.target_transforms]
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/datasets/coco.py", line 168, in <listcomp>
    anns = [t(image, anns, meta) for t in self.target_transforms]
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/encoder/cif.py", line 26, in __call__
    return CifGenerator(self)(image, anns, meta)
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/encoder/cif.py", line 52, in __call__
    self.fill(keypoint_sets)
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/encoder/cif.py", line 78, in fill
    [kps for i, kps in enumerate(keypoint_sets) if i != kps_i],
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/encoder/cif.py", line 117, in fill_keypoints
    self.fill_coordinate(f, xyv, joint_scale, max_r)
  File "/home.nfs/joao.gondim/openpifpaf/openpifpaf/encoder/cif.py", line 145, in fill_coordinate
    assert np.isnan(scale) or scale > 0.0
AssertionError`

I wonder if you, or anyone else has seen such error before.

**Comment by svenkreiss** [comment]
Looks like one of your joint scales is not valid. They should always be larger than zero.

**Comment by gondimjoaom** [comment]
It has something to do with the keypoints json. Thanks!
