### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'shufflenetv2k16w' | Ubuntu, Miniconda

### ISSUE THREAD

**Issue by AksharSharma** [vita-epfl/openpifpaf#331]
Hi 
I face the following error when I try to run a basic skeleton detection program. Help is much appreciated!
Traceback (most recent call last):
  File "skeleton_img_check.py", line 32, in <module>
    net_cpu, _ = openpifpaf.network.factory(checkpoint='shufflenetv2k16w', download_progress=True)
  File "/home/ubuntu/miniconda3/envs/latest_lib/lib/python3.8/site-packages/openpifpaf/network/factory.py", line 156, in factory
    checkpoint = torch.load(checkpoint)
  File "/home/ubuntu/miniconda3/envs/latest_lib/lib/python3.8/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ubuntu/miniconda3/envs/latest_lib/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ubuntu/miniconda3/envs/latest_lib/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'shufflenetv2k16w'

**Comment by svenkreiss** [comment]
remove the last `w` in the checkpoint name
