### ISSUE TITLE
Export_onnx with 0.12: "TypeError: 'module' object is not callable"

### ISSUE THREAD

**Issue by adujardin** [vita-epfl/openpifpaf#352]
Hi

The 0.12 release may have introduced a regression in the `export_onnx` script. When running it output `TypeError: 'module' object is not callable`. At first, I thought I misconfigured something but it's reproducible within docker like this:

```sh
# Run one or the other
docker run --gpus all -it nvidia/cuda:11.0-devel-ubuntu18.04
docker run -it ubuntu:18.04

# Then within the container:
apt update ; apt install python3-dev python3-pip -y
pip3 install numpy cython ; pip3 install openpifpaf matplotlib
# 'predict' works fine
python3 -m openpifpaf.export_onnx
```

Here's the error:
```
root@d75f11105e38:/# python3 -m openpifpaf.export_onnx
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/openpifpaf/export_onnx.py", line 152, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/openpifpaf/export_onnx.py", line 139, in main
    model, _ = openpifpaf.network.factory(checkpoint=args.checkpoint)
TypeError: 'module' object is not callable
```

Were you able to successfully run export_onnx with 0.12 before? Was there a folder reorganization or something that could cause a name conflict?

**Comment by svenkreiss** [comment]
Thanks for the report. A work-around for a pylint-pytorch bug disabled the error message that should have caught this during testing. I am fixing this right away.
