### ISSUE TITLE
ModuleNotFoundError: No module named 'openpifpaf.functional'

### ISSUE THREAD

**Issue by tqtrunghnvn** [vita-epfl/openpifpaf#369]
When running *openpifpaf.predict*, I am facing the error:
```
Traceback (most recent call last):
  File "/home/trung/anaconda2/envs/pifpaf/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/trung/anaconda2/envs/pifpaf/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/trung/workspace/pifpaf/openpifpaf/__init__.py", line 7, in <module>
    from .annotation import Annotation, AnnotationDet
  File "/home/trung/workspace/pifpaf/openpifpaf/annotation.py", line 6, in <module>
    from .functional import scalar_value_clipped
ModuleNotFoundError: No module named 'openpifpaf.functional'
```

Is there anyone completely solving this issue?

**Comment by svenkreiss** [comment]
This happens when you clone the repository and then don't install the python package.
Please follow the installation instructions: https://vita-epfl.github.io/openpifpaf/intro.html#install 
or follow the instructions that are linked under "Modify Code".

**Comment by tqtrunghnvn** [comment]
I got it. Thank you!
