### ISSUE TITLE
Export ONNX mobilenetv2 "Can't get attribute 'ConvBNReLU'"

### ISSUE THREAD

**Issue by adujardin** [vita-epfl/openpifpaf#387]
Hi,
Using the latest version I have this error while trying to export mobilenet models (resnet and shufflenet are working fine) into onnx

```
root@7156df29def4:/# python3 -m openpifpaf.export_onnx --checkpoint mobilenetv2
Downloading: "http://github.com/vita-epfl/openpifpaf-torchhub/releases/download/v0.12a5/mobilenetv2-201112-193315-cocokp-1728a9f5.pkl" to /root/.cache/torch/hub/checkpoints/mobilenetv2-201112-193315-cocokp-1728a9f5.pkl
100.0%
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/openpifpaf/export_onnx.py", line 156, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/openpifpaf/export_onnx.py", line 142, in main
    model, _ = openpifpaf.network.Factory().factory()
  File "/usr/local/lib/python3.6/dist-packages/openpifpaf/network/factory.py", line 177, in factory
    net_cpu, epoch = self.from_checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/openpifpaf/network/factory.py", line 244, in from_checkpoint
    progress=self.download_progress)
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 528, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'ConvBNReLU' on <module 'torchvision.models.mobilenet' from '/usr/local/lib/python3.6/dist-packages/torchvision/models/mobilenet.py'>
```

To replicate:
```sh
docker run -it ubuntu:18.04

# Then within the container, setup pifpaf:
apt update ; apt install python3-dev python3-pip -y
pip3 install numpy cython ; pip3 install openpifpaf matplotlib

python3 -m openpifpaf.export_onnx # Working (resnet50)
python3 -m openpifpaf.export_onnx --checkpoint mobilenetv2 # Error
```

Am I doing something wrong maybe?

**Comment by svenkreiss** [comment]
This seems to be related to #388 . I cannot reproduce this error on my machine but I'll try your Docker commands.

**Comment by svenkreiss** [comment]
I can reproduce the problem inside the docker container. For future reference, I first upgrade pip and setuptools and then use the cpu-only version of torch:

```
python3 -m pip install --upgrade pip setuptools
python3 -m pip install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.htm
python3 -m pip install openpifpaf
```

Investigating now why mobilenetv2 fails ...

**Comment by svenkreiss** [comment]
Unfortunately, you'd have to downgrade torchvision to 0.8.2 to make this work. Details are in #388.
