### ISSUE TITLE
Cannot change the model to something other than shufflenetv2k16

### ISSUE THREAD

**Issue by Ethan0104** [vita-epfl/openpifpaf#388]
Hello again, I am still playing with the Predict API code and I wanted to try changing the model to something else. Specifically, I am changing the line: 
`net_cpu, _ = openpifpaf.network.Factory(checkpoint='shufflenetv2k16', download_progress=False).factory()`
to
`net_cpu, _ = openpifpaf.network.Factory(
        checkpoint='mobilenetv2', download_progress=False).factory()`
But when I do that, I get this weird error: 
`Downloading: "http://github.com/vita-epfl/openpifpaf-torchhub/releases/download/v0.12a5/mobilenetv2-201112-193315-cocokp-1728a9f5.pkl" to /Users/ethan/.cache/torch/hub/checkpoints/mobilenetv2-201112-193315-cocokp-1728a9f5.pkl
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ethan/Desktop/AAA_Programming/Monitor_System/main.py", line 60, in <module>
    net, decoder, preprocess, annotation_painter = setup_model()
  File "/Users/ethan/Desktop/AAA_Programming/Monitor_System/main.py", line 20, in setup_model
    checkpoint='mobilenetv2', download_progress=False).factory()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/openpifpaf/network/factory.py", line 177, in factory
    net_cpu, epoch = self.from_checkpoint()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/openpifpaf/network/factory.py", line 244, in from_checkpoint
    progress=self.download_progress)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/hub.py", line 524, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/hub.py", line 394, in download_url_to_file
    u = urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>`
Is there something I am doing wrong?

**Comment by Ethan0104** [comment]
I fixed the certificate issue with the solution here[](https://stackoverflow.com/questions/49183801/ssl-certificate-verify-failed-with-urllib), but now I have a new error: 
`Downloading: "http://github.com/vita-epfl/openpifpaf-torchhub/releases/download/v0.12a5/mobilenetv2-201112-193315-cocokp-1728a9f5.pkl" to /Users/ethan/.cache/torch/hub/checkpoints/mobilenetv2-201112-193315-cocokp-1728a9f5.pkl
Traceback (most recent call last):
  File "/Users/ethan/Desktop/AAA_Programming/Monitor_System/main.py", line 60, in <module>
    net, decoder, preprocess, annotation_painter = setup_model()
  File "/Users/ethan/Desktop/AAA_Programming/Monitor_System/main.py", line 20, in setup_model
    checkpoint='mobilenetv2', download_progress=False).factory()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/openpifpaf/network/factory.py", line 177, in factory
    net_cpu, epoch = self.from_checkpoint()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/openpifpaf/network/factory.py", line 244, in from_checkpoint
    progress=self.download_progress)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/hub.py", line 528, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'ConvBNReLU' on <module 'torchvision.models.mobilenet' from '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torchvision/models/mobilenet.py'>`

**Comment by svenkreiss** [comment]
I just tested `mobilenetv2`, `resnet50` and `shufflenetv2k30`. All work on my machine.
Which torch and torchvision versions are you using (`pip freeze | grep torch`)?

**Comment by svenkreiss** [comment]
Alright, due to the new mobilenetv3, the models in torch vision got renamed from `mobilenet` to `mobilenet_v2`. That broke loading the checkpoint with newer torchvision.

These versions work with that checkpoint:

```
torch==1.7.1
torchvision==0.8.2
``` 

Just a little warning, I never saw good performance with mobilenet and the shufflenetv2k16 model performs a lot better.

**Comment by agrija9** [comment]
Hi @svenkreiss, 

Regarding model performance, I also want to create the onnx file for MobilenetV2 since it seems to be smaller than most of the available pretrained models. 

I am trying to run inference on a Jetson Xavier NX, I have tried doing this with other models like ResNet50 but my board can't handle such model sizes (it freezes and kills the process).

Do you have any inputs on this?
